name: Sync to Hugging Face Hub

on:
  push:
    branches: [main] # Or 'master' if your default branch is master
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # REPLACE 'YOUR_USERNAME' and 'YOUR_SPACE_NAME' BELOW!
        run: git push --force https://YOUR_USERNAME:$HF_TOKEN@huggingface.co/spaces/YOUR_USERNAME/YOUR_SPACE_NAME main